package ua.stqa.aqa.addressbook.tests;// Generated by Selenium IDE

import org.testng.Assert;
import org.testng.annotations.Test;
import ua.stqa.aqa.addressbook.model.GroupData;

public class GroupCreationTests extends TestBase {


  @Test
  public void testGroupCreation() {
    //int before=app.getGroupHelper().getGroupCount();
    app.getNavigationHelper().gotoGroupPage();
    int before=app.getGroupHelper().getGroupCount();
    app.getGroupHelper().createGroup(new GroupData("test1", null, "testc"));
    int after=app.getGroupHelper().getGroupCount();
    System.out.println(before);
    System.out.println(after);
    Assert.assertEquals(after,before+1);
  }

}
