package ua.stqa.aqa.addressbook.tests;// Generated by Selenium IDE

import org.testng.Assert;
import org.testng.annotations.Test;
import ua.stqa.aqa.addressbook.model.GroupData;

public class GroupDeletionTests extends TestBase {

  @Test
  public void testGroupDeletion() {
    app.getNavigationHelper().gotoGroupPage();
    int before=app.getGroupHelper().getGroupCount();
    if(! app.getGroupHelper().IsThereAGroup()){
      app.getGroupHelper().createGroup(new GroupData("test1", null, "testc"));
    }
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnToGroupPage();

    int after=app.getGroupHelper().getGroupCount();
    System.out.println(before);
    System.out.println(after);
    Assert.assertEquals(after,before-1);
  }

}
