package ua.stqa.aqa.addressbook.tests;// Generated by Selenium IDE

import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import ua.stqa.aqa.addressbook.model.GroupData;

import java.util.List;

public class GroupDeletionTests extends TestBase {
  @BeforeMethod
  public void ensurePreconditions() {
    app.goTo().groupPage();
    if (app.group().list().size()==0) {
      app.group().create(new GroupData().withName("test"));
    }
  }

  @Test
  public void testGroupDeletion() {
    List<GroupData> before=app.group().list();
    int index=before.size()-1;
    app.group().delete(index);
    List<GroupData> after=app.group().list();
    //int before=app.getGroupHelper().getGroupCount();
    //int after=app.getGroupHelper().getGroupCount();
    System.out.println(before.size());
    System.out.println(after.size());
    Assert.assertEquals(after.size(),before.size()-1);

    before.remove(index);
    Assert.assertEquals(before,after);

  }



}
